Repository Alexeys-cats/HTML-lessons, pull requests merged in 2025-07, with the labels that each got.

#31 btn
  package-lock.json
  package.json
  src/components/Header.tsx
  src/components/Mainbtn.tsx
  src/index.css
  src/utils/utils.ts
Labels: feature, UI

#44 Feature/setup ci
  .github/workflows/check.yml
  .prettierignore
  .prettierrc
  README.md
  eslint.config.js
  package-lock.json
  package.json
  postcss.config.mjs
  src/App.tsx
  src/assets/dataJson/data-css.json
  src/assets/dataJson/data-html.json
  src/assets/dataJson/data-quiz.json
  src/components/Header.tsx
  src/index.css
  src/pages/Home.tsx
  src/utils/utils.ts
  vite.config.ts
Labels: enhancement, 🌟Easy

#51 Task-#20-create-home-page
  public/CSSImg.png
  public/HTMLImg.png
  public/JSImg.png
  public/ReacktImg.png
  public/animatedHomePageImg.svg
  public/homeImg.png
  public/nextImg.png
  public/tailwindImg.png
  public/tsImg.png
  src/components/AnimatedImg.tsx
  src/index.css
  src/pages/Home.tsx
Labels: feature, UI, 🌟Easy

#53 fix img import
  src/components/AnimatedImg.tsx
  src/components/Header.tsx
  src/pages/Home.tsx
Labels: bug

#60 refact header component
  src/App.tsx
  src/components/Header.tsx
  src/components/Menu.tsx
  src/components/Modal/Modal.stories.tsx
  src/features/AuthByUserName/ui/AuthByUserName.tsx
  src/pages/Home.tsx
  src/shared/assets/logo.svg
  src/shared/dataJson/data-css.json
  src/shared/dataJson/data-html.json
  src/shared/dataJson/data-quiz.json
  src/shared/react.svg
  src/shared/ui/Button/Button.stories.ts
  src/shared/ui/Button/Button.tsx
  src/shared/ui/Input/Input.stories.tsx
  src/shared/ui/Input/Input.tsx
  src/shared/ui/Input/readme.txt
  src/shared/ui/Text/Text.stories.tsx
  src/shared/ui/Text/Text.tsx
  src/widgets/Header/AppLink.tsx
  src/widgets/Header/Header.tsx
  src/widgets/Header/HeaderComponents/BurgerButton.tsx
  src/widgets/Header/HeaderComponents/DesktopNav.tsx
  src/widgets/Header/HeaderComponents/MobileMenu.tsx
  src/widgets/Header/HeaderComponents/SearchInput.tsx
Labels: enhancement, 🌟Easy, UX
